# -*- coding: utf-8 -*-
"""IBS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfuVm8UEuPRxNUFYl06fWw5J11TIw-_w
"""

import pandas as pd
import numpy as np
df = pd.read_csv('ibs.csv', encoding='latin1')

df.head()

df.isnull().sum()

df.info()

df = df.drop(columns=["Timestamp", "1. Name"])

"""Occupation"""

df.columns = df.columns.str.strip()
sorted(df['3. Occupation'].dropna().unique())

occ = df['3. Occupation'].str.casefold().str.replace(r'\s+', ' ', regex=True).str.strip()

df['Occupation_Clean'] = 'Other'

# Student
df.loc[occ.str.contains('student|mbbs|dpt|pharm|undergraduate|studying', na=False), 'Occupation_Clean'] = 'Student'

# Homemaker
df.loc[occ.str.contains('house|housewife|homemaker|hw', na=False), 'Occupation_Clean'] = 'Homemaker'

# Healthcare
df.loc[occ.str.contains('doctor|physician|dentist|nurse|physio|mo|hospital|microbiologist|homeopathic', na=False), 'Occupation_Clean'] = 'Healthcare Professional'

# Teacher
df.loc[occ.str.contains('teacher|lecturer|professor|headmistress|tutor', na=False), 'Occupation_Clean'] = 'Teacher/Education'

# Business
df.loc[occ.str.contains('business|freelancer|content|writer|parlour|baker', na=False), 'Occupation_Clean'] = 'Business/Self-employed'

# Office/Service
df.loc[occ.str.contains('accountant|bank|receptionist|secretary|call centre|computer operator|police|constable|waiter', na=False), 'Occupation_Clean'] = 'Office/Service'

# Technical/Professional
df.loc[occ.str.contains('engineer|designer|journalist|marketing|psychologist|chef|social worker', na=False), 'Occupation_Clean'] = 'Technical/Professional'

# Unemployed
df.loc[occ.str.contains('none|no occupation|no job|drop out', na=False), 'Occupation_Clean'] = 'Unemployed'

df['Occupation_Clean'].value_counts()

df['Occupation_Clean'] = df['Occupation_Clean'].fillna('Other')

df.loc[df['Occupation_Clean'].isna(), 'Occupation_Clean'] = 'Other'

df['Occupation_Clean'].info()

"""q15

"""

pain_col = '1. Abdominal pain\na. Do you currently suffer from abdominal (belly) pain?'

pain_severity_col = 'If yes, continue please:\nSeverity of abdominal pain:'

mask = (df[pain_col] == 'No') & (df[pain_severity_col].isna())

df.loc[mask, pain_severity_col] = 'No pain(0%)'

mask.sum()

df[pain_severity_col].isna().sum()

"""q16"""

pain_days_col = 'Number of days with pain (last 10 days):'

pd.crosstab(
    df[pain_col],
    df[pain_days_col].isna()
)

df[pain_days_col].info()

df.loc[
    (df[pain_col] == "Yes") &
    (df[pain_days_col].isna() == False),
    pain_days_col
].value_counts()

df.loc[df[pain_col] == "Yes", pain_days_col].unique()

"""1. Normalize text"""

df[pain_days_col] = (
    df[pain_days_col]
    .astype(str)
    .str.strip()
    .str.casefold()
)

"""2.replace text with numbers"""

df[pain_days_col] = df[pain_days_col].replace({
    'no': '0',
    'no any': '0',
    'a week': '7',
    '1 week': '7',
    '1 week ': '7'
})

"""3.Number extraction"""

df[pain_days_col] = df[pain_days_col].str.extract(r'(\d+)', expand=False)

"""4.Convert to numeric"""

df[pain_days_col] = pd.to_numeric(df[pain_days_col], errors='coerce')

"""5.Remove impossible values"""

df.loc[df[pain_days_col] > 10, pain_days_col] = np.nan

"""6.Recheck"""

pd.crosstab(
    df[pain_col],
    df[pain_days_col].isna()
)

"""7.Inspect 5 missing rows with previous answer of no abdominal pain and filling them"""

df.loc[
    (df[pain_col] == 'No') &
    (df[pain_days_col].notna()),
    [pain_col, pain_days_col]
]

df.loc[
    (df[pain_col] == 'No') &
    (df[pain_days_col].isna()),
    [pain_col, pain_days_col]
]

mask = (df[pain_col] == 'No') & (df[pain_days_col].isna())
df.loc[mask, pain_days_col] = 0

pd.crosstab(
    df[pain_col],
    df[pain_days_col].isna()
)

"""NAN values in 12 rows preserved"""

df.loc[
    (df[pain_col] == 'Yes') &
    (df[pain_days_col].isna()),
    pain_days_col
]

df[pain_days_col].isna().sum()



"""Q.17 & 18 1.Define columns"""

bloat_col = '2. Abdominal Distension (Bloating);\na. Do you experience abdominal distension (bloating)?'

severity_col = 'If Yes, continue:\nSeverity of distension:'

"""2.check skip logic"""

pd.crosstab(
    df[bloat_col],
    df[severity_col].isna()
)

"""3.Fill justified missing values"""

mask = (df[bloat_col] == 'No') & (df[severity_col].isna())

df.loc[mask, severity_col] = 'No distension (0%)'

df.loc[
    (df[bloat_col] == 'No') &
    (df[severity_col].notna()),
    [bloat_col, severity_col]
]

"""Recheck"""

pd.crosstab(
    df[bloat_col],
    df[severity_col].isna()
)

df.loc[
    (df[bloat_col] == 'Yes') &
    (df[severity_col].isna()),
    [bloat_col, severity_col]
]

"""In total 15 participants out of 320 had atleast 1 variable missing these participant were retained in cleaned data set by assigning them NAN values may be deleted if requested by the researcher. Analyst recommendation is to preserve useful data in rest of the variables answer and do not delete them

Locate missing 1 value q15
"""

df.loc[df[pain_severity_col].isna(),
       [pain_col, pain_severity_col]]
df[df[pain_severity_col].isna()].index

"""Locate missing 12 value q16"""

df.loc[df[pain_days_col].isna(),
       [pain_col, pain_days_col]]
df[df[pain_days_col].isna()].index

"""Locate 2 missing value q18"""

df.loc[df[severity_col].isna(),
       [bloat_col, severity_col]]
df[df[severity_col].isna()].index

missing_rows = df[
    df[[pain_severity_col, pain_days_col, severity_col]]
    .isna()
    .any(axis=1)
]

print(missing_rows.shape)

# Number of participants with at least one remaining missing value
missing_rows = df[
    df[[pain_severity_col,
        pain_days_col,
        severity_col]]
    .isna()
    .any(axis=1)
]

print(f"Participants with remaining missing values: {missing_rows.shape[0]}")

missing_rows[[
    pain_col,
    pain_severity_col,
    pain_days_col,
    bloat_col,
    severity_col
]].reset_index()

df.info()

df.head()

"""Cleaning pss questions 1 to 10"""

pss_cols = [
    '1. Been upset because something happened unexpectedly?',
    '2. Felt unable to control important things in your life?',
    '3. Felt nervous and \x93stressed\x94?',
    '4. Felt confident about handling personal problems?',
    '5. Felt that things were going your way?',
    '6. Found you could not cope with all the things you had to do?',
    '7. Been able to control irritations in your life?',
    '8. Felt that you were on top of things?',
    '9. Been angered because of things outside your control?',
    '10. Felt difficulties were pulling up so high that you could not overcome them?'
]
for col in pss_cols:
    df[col] = (
        df[col]
        .str.extract(r'(\d+)', expand=False)
        .astype(int)
    )

"""verification"""

df[pss_cols].head()

for col in pss_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype(int)

df[pss_cols].dtypes

df.head()

"""Final cleaning column renaming for convinience"""

df = df.drop(columns=['3. Occupation'], errors='ignore')
df = df.rename(columns={'Occupation_Clean': 'Occupation'})

df = df.rename(columns={

    # Demographics
    '2. Age:': 'Age_Group',
    'Occupation': 'Occupation',

    # PSS-10 Items
    '1. Been upset because something happened unexpectedly?': 'PSS_UpsetUnexpectedly',
    '2. Felt unable to control important things in your life?': 'PSS_LackofControl',
    '3. Felt nervous and stressed?': 'PSS_Stressed',
    '4. Felt confident about handling personal problems?': 'PSS_Confident',
    '5. Felt that things were going your way?': 'PSS_Thingsgoingwell',
    '6. Found you could not cope with all the things you had to do?': 'PSS_CouldNotCope',
    '7. Been able to control irritations in your life?': 'PSS_ControlIrritations',
    '8. Felt that you were on top of things?': 'PSS_OnTopOfThings',
    '9. Been angered because of things outside your control?': 'PSS_Angered',
    '10. Felt difficulties were pulling up so high that you could not overcome them?':
        'PSS_Overwhelmed',

    # IBS-SSS
    '1. Abdominal pain\na. Do you currently suffer from abdominal (belly) pain?': 'Abdominal_Pain',
    'If yes, continue please:\nSeverity of abdominal pain:': 'Pain_Severity', 'Number of days with pain (last 10 days):': 'Pain_Days',
    '2. Abdominal Distension (Bloating);\na. Do you experience abdominal distension (bloating)?': 'Abdominal_Distension',
    'If Yes, continue:\nSeverity of distension:': 'Distension_Severity',


    '3. Satisfaction with Bowel Habits:\nIndicate your satisfaction level:':
        'Bowel_Satisfaction',

    '4. Interference with Daily Life\nHow much does IBS affect your daily life?':
        'DailyLife_Interference'
})

df.head()

df.info()

"""saving cleaned file

"""

df.to_csv("IBS_Cleaned.csv", index=False)

from google.colab import files

files.download("IBS_Cleaned.csv")