# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRfep2wR5D-NWHJUk6xgTug6HLJrN8M-

1 Introduction

2 Import Libraries

3 Load Dataset

4 Dataset Overview

5 Missing Values

6 Demographic Analysis

7 PSS Analysis

8 IBS Analysis

9 Numerical Variable Analysis

10 Correlation Analysis

11 PSS Total Score

12 Relationship Analysis

13 Statistical Tests

14 Key Insights
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import chi2_contingency

"""TABLE 1 DEMOGRAPHICS"""

# Function to create frequency and percentage table
def freq_table(df, column):
    table = (
        df[column]
        .value_counts(dropna=False)
        .rename_axis('Category')
        .reset_index(name='Frequency')
    )

    table['Percentage (%)'] = (
        table['Frequency'] / len(df) * 100
    ).round(1)

    table.insert(0, 'Variable', column)

    return table

# Load the dataset (assuming 'IBS_Cleaned.csv' is the correct file)
df = pd.read_csv('/content/IBS_Cleaned .csv')

age_table = freq_table(df, 'Age_Group')
occupation_table = freq_table(df, 'Occupation')
demographic_table = pd.concat(
    [age_table, occupation_table],
    ignore_index=True
)

demographic_table

demographic_table.style.hide(axis="index")

demographic_table['Percentage (%)'] = demographic_table['Percentage (%)'].round(1)
demographic_table.loc[
    demographic_table['Variable'].duplicated(), 'Variable'
] = ''

display(demographic_table.style.hide(axis='index'))

demographic_table.to_excel("Table1_Demographics.xlsx", index=False)

from google.colab import files
files.download("Table1_Demographics.xlsx")

"""TABLE 2 PSS"""

# ===========================
# CLEAN PSS SCORING + TABLE 4
# ===========================

import pandas as pd
from scipy.stats import chi2_contingency

# -----------------------------
# Detect stressed question automatically
# -----------------------------
stress_col = [c for c in df.columns if "stressed" in c.lower()][0]

# PSS Items (10)
pss_cols = [
    'PSS_UpsetUnexpectedly',
    'PSS_LackofControl',
    stress_col,
    'PSS_Confident',
    'PSS_Thingsgoingwell',
    'PSS_CouldNotCope',
    'PSS_ControlIrritations',
    'PSS_OnTopOfThings',
    'PSS_Angered',
    'PSS_Overwhelmed'
]

# Reverse-scored items
reverse_cols = [
    'PSS_Confident',
    'PSS_Thingsgoingwell',
    'PSS_ControlIrritations',
    'PSS_OnTopOfThings'
]

df_pss = df.copy()

# Reverse scoring
df_pss[reverse_cols] = 4 - df_pss[reverse_cols]

# Total PSS
df_pss["PSS_Total"] = df_pss[pss_cols].sum(axis=1)

# Stress Categories
df_pss["Stress_Level"] = pd.cut(
    df_pss["PSS_Total"],
    bins=[-1,13,26,40],
    labels=["Low","Moderate","High"]
)

# -----------------------------
# Chi-square Analysis
# -----------------------------
ibs_vars = {
    "Pain_Severity":"Pain Severity",
    "Distension_Severity":"Distension Severity",
    "Bowel_Satisfaction":"Bowel Satisfaction",
    "DailyLife_Interference":"Daily Life Interference"
}

results=[]

for col,label in ibs_vars.items():

    temp=df_pss[["Stress_Level",col]].dropna()

    contingency=pd.crosstab(
        temp["Stress_Level"],
        temp[col]
    )

    chi2,p,dof,expected=chi2_contingency(contingency)

    cells_lt5=(expected<5).sum()
    total_cells=expected.size

    results.append({
        "IBS Variable":label,
        "N":len(temp),
        "Chi-square":round(chi2,2),
        "df":dof,
        "P-value":round(p,4),
        "% Expected <5":round(cells_lt5/total_cells*100,1),
        "Significant":"Yes" if p<0.05 else "No"
    })

table4=pd.DataFrame(results)

print(table4)

display(table4)

table4.to_excel("Table4_ChiSquare.xlsx",index=False)

# ==========================================
# TABLE: Stress Level Distribution (PSS-10)
# ==========================================

stress_summary = (
    df_pss["Stress_Level"]
    .value_counts(sort=False)
    .rename_axis("Stress Level")
    .reset_index(name="Frequency")
)

stress_summary["Percentage (%)"] = (
    stress_summary["Frequency"] / len(df_pss) * 100
).round(2)

# Display


# Optional formatting
display(stress_summary.style.hide(axis="index"))

# Save to Excel
stress_summary.to_excel("Stress_Level_Summary.xlsx", index=False)

from google.colab import files
files.download("Stress_Level_Summary.xlsx")

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming ibs_vars is defined globally from previous cells
ibs_vars = {
    'Pain_Severity': 'Pain Severity',
    'Distension_Severity': 'Distension Severity',
    'Bowel_Satisfaction': 'Bowel Satisfaction',
    'DailyLife_Interference': 'Daily Life Interference'
}

# Create a copy to avoid modifying the original df_pss directly for this operation
# and ensure only the relevant columns are processed.
df_pss_corr = df_pss[list(ibs_vars.keys()) + ['PSS_Total']].copy()

# Define ordinal mappings for IBS variables
pain_severity_mapping = {
    'No pain(0%)': 0,
    'Mild': 1,
    'Moderate': 2,
    'Severe': 3,
    'Very severe (100%)': 4
}
distension_severity_mapping = {
    'No distension (0%)': 0,
    'Mild': 1,
    'Moderate': 2,
    'Severe': 3,
    'Very severe': 4 # Assuming this means 100%
}
bowel_satisfaction_mapping = {
    'Not at all satisfied (0%)': 0,
    'Somewhat satisfied': 1,
    'Moderately satisfied': 2,
    'Very satisfied (100%)': 3
}
dailylife_interference_mapping = {
    'Not at all': 0,
    'Mild': 1,
    'Moderate': 2,
    'Severe': 3,
    '100% completely interferes': 4
}

# Apply the mappings to the respective columns in df_pss_corr
df_pss_corr['Pain_Severity'] = df_pss_corr['Pain_Severity'].map(pain_severity_mapping)
df_pss_corr['Distension_Severity'] = df_pss_corr['Distension_Severity'].map(distension_severity_mapping)
df_pss_corr['Bowel_Satisfaction'] = df_pss_corr['Bowel_Satisfaction'].map(bowel_satisfaction_mapping)
df_pss_corr['DailyLife_Interference'] = df_pss_corr['DailyLife_Interference'].map(dailylife_interference_mapping)

# Columns to include in the correlation matrix (now all should be numeric)
correlation_cols = list(ibs_vars.keys()) + ['PSS_Total']

# Calculate the Spearman correlation matrix
corr_matrix = df_pss_corr[correlation_cols].corr(method='spearman')

# Extract only PSS correlations
pss_corr = corr_matrix[['PSS_Total']].drop('PSS_Total')

plt.figure(figsize=(5,4))

sns.heatmap(
    pss_corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5,
    cbar_kws={"label": "Spearman ρ"}
)

plt.title(
    "Figure 1: Correlation of PSS Total with IBS Symptom Domains",
    fontsize=12,
    pad=12
)

plt.ylabel("")
plt.xlabel("")

plt.tight_layout()
plt.show()
